[versions]
room = "2.5.1"
okhttp = "5.0.0-alpha.11"
navigation = "2.5.3"
hilt = "2.46.1"
coroutines = "1.7.1"
lifecycle = "2.6.1"
retrofit = "2.9.0"
androidGradlePlugin = "8.0.1"

[libraries]
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }

gson = { group = "com.google.code.gson", name = "gson", version = "2.10.1" }

coil = { group = "io.coil-kt", name = "coil", version = "2.4.0" }

firebase-crashlytics = { group = "com.google.firebase", name = "firebase-crashlytics-ktx", version = "18.3.7" }
firebase-analytics = { group = "com.google.firebase", name = "firebase-analytics-ktx", version = "21.2.2" }
firebase-pref = { group = "com.google.firebase", name = "firebase-perf-ktx", version = "20.3.2" }

okhttp = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp" }
logging-interceptor = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "okhttp" }

navigation-fragment = { group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref = "navigation" }
navigation-ui = { group = "androidx.navigation", name = "navigation-ui-ktx", version.ref = "navigation" }

hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "hilt" }

coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutines" }
coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutines" }

lifecycle-viewmodel = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
lifecycle-livedata = { group = "androidx.lifecycle", name = "lifecycle-livedata-ktx", version.ref = "lifecycle" }

retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
retrofit-converter = { group = "com.squareup.retrofit2", name = "converter-gson", version.ref = "retrofit" }

constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version = "2.1.4" }

android-material = { group = "com.google.android.material", name = "material", version = "1.9.0" }

android-appcompat = { group = "androidx.appcompat", name = "appcompat", version = "1.6.1" }

android-core = { group = "androidx.core", name = "core-ktx", version = "1.10.1"}

# Testing
junit = { group = "junit", name = "junit", version = "4.13.2" }
truth = { group = "com.google.truth", name = "truth", version = "1.1.3" }
coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "coroutines" }
core-testing = { group = "androidx.arch.core", name = "core-testing", version = "2.2.0"}

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
android-library = { id = "com.android.library", version.ref = "androidGradlePlugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version = "1.8.0" }
hilt-plugin = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
